version: '2'
services:
  miniblog-uwsgi:
    image: miniblog-uwsgi
    container_name: miniblog-uwsgi
    depends_on:
      - miniblog-mysql
    links:
      - "miniblog-mysql:miniblog-mysql"
    volumes:
      - .:/app/
    env_file: ./miniblog/settings/local.env
    environment:
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}"

  miniblog-nginx:
    image: miniblog-nginx
    container_name: miniblog-nginx
    depends_on:
      - miniblog-uwsgi
    links:
      - "miniblog-uwsgi:miniblog-uwsgi"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    environment:
      - UWSGI_URI=miniblog-uwsgi:30000
      - "SERVER_NAME=${WEB_HOST}"
      - "VIRTUAL_HOST=${WEB_HOST}"

  miniblog-mysql:
    image: miniblog-mysql
    container_name: miniblog-mysql
    ports:
      - "3306:3306"
    volumes_from:
      - miniblog-mysql-data
    depends_on:
      - miniblog-mysql-data
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"

  miniblog-mysql-data:
    image: mysql:latest
    container_name: miniblog-mysql-data
    volumes:
      - mysql-data:/var/lib/mysql/data
    entrypoint: /bin/bash
    privileged: true

  miniblog-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: miniblog-phpmyadmin
    links:
      - "miniblog-mysql:mysql"
    environment:
      - "MYSQL_USERNAME=${MYSQL_USERNAME}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "PMA_HOST=${PMA_HOST}"
      - "PMA_ABSOLUTE_URI=http://${DB_HOST}"
      - "VIRTUAL_HOST=${DB_HOST}"

  miniblog-reverse-proxy:
    image: jwilder/nginx-proxy
    container_name: miniblog-reverse-proxy
    ports:
      - "80:80"
    volumes_from:
      - miniblog-nginx
    links:
      - miniblog-nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /tmp/nginx.tmpl:/etc/docker-gen/templates

volumes:
  mysql-data:
    external: true

