# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
    ]
